Create Item production BOM and Item
aerele/apparelo pull request #3
Opened 2019-10-04 10:49 UTC by Ayivak

2019-10-05 06:29 UTC, karthikeyan5 requested changes

2019-10-05 06:29 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/item_production_detail/item_production_detail.json
> +  },
Please remove this field and set autoname as "Prompt" instead.

2019-10-05 06:29 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/item_production_detail/item_production_detail.json
> +   "fieldname": "item",
set this as mandatory?

2019-10-08 04:01 UTC, Vigneshsekar commented
![screenshot](https://user-images.githubusercontent.com/11339902/66366516-51f36e00-e9ae-11e9-95d8-764d28fb8361.png)
![screenshot](https://user-images.githubusercontent.com/11339902/66366521-561f8b80-e9ae-11e9-890f-b1265f734efc.png)


Shall we the same font size here?

2019-10-08 04:02 UTC, Vigneshsekar commented
![screenshot](https://user-images.githubusercontent.com/11339902/66366544-6cc5e280-e9ae-11e9-923a-b64d0709f747.png)


Here too, we shall have the same font throughout the page...

2019-10-08 04:05 UTC, karthikeyan5 approved these changes

2019-10-08 05:05 UTC, merged