Convert Dia as a float field to a Link field
aerele/apparelo pull request #83
Opened 2020-01-25 12:14 UTC by Vigneshsekar

Fixes #73 
Fixes #71 
Fixes #69 
Fixes #68 

If this PR is getting merged, we need to manually alter the Dia in the templates.

2020-01-25 17:39 UTC, KaviyaPeriyasamy requested changes
Need to change the dia attribute in the roll printing template.

2020-01-27 05:50 UTC, karthikeyan5 requested changes

2020-01-27 05:50 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/apparelo_dia/apparelo_dia.py
> +		item_attribute.save()
push this into the if condition... do this for all other doctypes too...

2020-01-27 05:50 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/cutting/cutting.py
> +				attribute_value.add(str(detail.dia))
remove `str()`

2020-01-27 05:50 UTC, karthikeyan5 commented on apparelo/apparelo/patches/v1/dia_to_apparelo_dia.py
> +	frappe.db.commit()
remove `db.commit` ?

2020-01-27 05:57 UTC, karthikeyan5 approved these changes

2020-01-27 05:58 UTC, merged