Additional parts
aerele/apparelo pull request #92
Opened 2020-02-03 07:28 UTC by Ayivak

Fixes #79
The creation of additional parts with color and size mapping, adding filters for item field in respective doctypes, creation of item group for the intermediate product.

2020-02-04 09:26 UTC, karthikeyan5 requested changes

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.js
> +		frm.set_query("additional_items", function() {
is it possible send these filters to a single file and include here?

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.js
> +					"item_group":"Raw Material",
add `Has Variants` filter also... here and all other related places

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.json
> +  "items",
can we rename this to a more related name? something like `size_additional_items`?

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.json
> +  "additional_items",
same as above... `color_additional_item`?

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.json
> +  "additional_items",
also do the same for all other doctypes....

2020-02-04 09:26 UTC, karthikeyan5 commented on apparelo/apparelo/doctype/stitching/stitching.py
> +				for additional_ in self.additional_parts:
rename to `additional_part`

2020-02-04 19:28 UTC, KaviyaPeriyasamy commented on apparelo/apparelo/doctype/stitching/stitching.py
> +				for additional_ in self.additional_parts:
This commit resolve all the changes 749652cfbf24ee57d93d639b3057e167e86064bb

2020-02-05 11:02 UTC, karthikeyan5 requested changes
issues found: 
- [x] `Get Piece Color` and `Get Piece Size` Button not working... getting error following error
<details>
<summary>Traceback</summary>

```Python traceback
Traceback (most recent call last):
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/__init__.py", line 1059, in call
    return fn(*args, **newargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/apparelo/apparelo/apparelo/doctype/stitching/stitching.py", line 225, in get_additional_item_piece_colour
    for item in doc.get('items'):
TypeError: 'NoneType' object is not iterable
```
</details>

- [x] submit IPD is not working getting the following error
<details>
<summary>Traceback</summary>

```Python traceback
Traceback (most recent call last):
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 875, in submit
    self._submit()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 864, in _submit
    self.save()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 277, in save
    return self._save(*args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 330, in _save
    self.run_post_save_methods()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 941, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 803, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 1090, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 1073, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 797, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/apparelo/apparelo/apparelo/doctype/item_production_detail/item_production_detail.py", line 18, in on_submit
    ipd_list=self.create_process_details()
  File "/home/karthi/frappe/benches/dev-bench/apps/apparelo/apparelo/apparelo/doctype/item_production_detail/item_production_detail.py", line 219, in create_process_details
    bom,new_variants=cutting_doc.create_boms(input_items, variants, attribute_set,item_size,colour,piece_count)
  File "/home/karthi/frappe/benches/dev-bench/apps/apparelo/apparelo/apparelo/doctype/cutting/cutting.py", line 119, in create_boms
    bom_doc=frappe.get_doc("BOM",bom_)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/__init__.py", line 747, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 71, in get_doc
    return controller(*args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/website/website_generator.py", line 16, in __init__
    super(WebsiteGenerator, self).__init__(*args, **kwargs)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/__init__.py", line 372, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/__init__.py", line 358, in msgprint
    _raise_exception()
  File "/home/karthi/frappe/benches/dev-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: BOM None not found
```
</details>

2020-02-07 16:02 UTC, merged